add actions for multi-loader
Signed-off-by: Lenson <nosnelmil@gmail.com>

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -1,13 +1,13 @@
 name: End-to-End Tests
 
 on:
- schedule:
-   - cron: "0 9 * * 1"
- workflow_dispatch:
- push:
-   branches: [main]
- pull_request:
-   branches: [main]
+  schedule:
+    - cron: "0 9 * * 1"
+  workflow_dispatch:
+  push:
+    branches: [main, multi-loader-actions]
+  pull_request:
+    branches: [main]
 
 env:
   GOOS: linux
@@ -20,7 +20,6 @@ jobs:
       KIND_VERSION: v0.22.0
       K8S_VERSION: v1.29
       YAML_DIR: workloads/container
-
     runs-on: ubuntu-20.04
     strategy:
       fail-fast: false
@@ -30,33 +29,8 @@ jobs:
             trace_func_go,
           ]
     steps:
-      - uses: actions/checkout@v4
-        with:
-          lfs: "true"
-      - name: Checkout LFS objects
-        run: git lfs checkout
-
-      - uses: actions/setup-go@v5
-        with:
-          go-version: 1.22
-
-      - name: Create k8s Kind Cluster
-        run: bash ./scripts/konk-ci/01-kind.sh
-
-      - name: Install Serving
-        run: bash ./scripts/konk-ci/02-serving.sh
-
-      - name: Install Kourier
-        run: bash ./scripts/konk-ci/02-kourier.sh
-
-      - name: Setup domain and autoscaler
-        run: |
-          INGRESS_HOST="127.0.0.1"
-          KNATIVE_DOMAIN=$INGRESS_HOST.sslip.io
-          kubectl patch configmap -n knative-serving config-domain -p "{\"data\": {\"$KNATIVE_DOMAIN\": \"\"}}"
-          kubectl patch configmap -n knative-serving config-autoscaler -p "{\"data\": {\"allow-zero-initial-scale\": \"true\"}}"
-          kubectl patch configmap -n knative-serving config-features -p "{\"data\": {\"kubernetes.podspec-affinity\": \"enabled\"}}"
-          kubectl label node knative-control-plane loader-nodetype=worker
+      - name: Set up common environment
+        uses: ./.github/workflows/ci-setup.yml
 
       - name: Build and run loader
         run: go run cmd/loader.go --config pkg/config/test_config.json
@@ -73,6 +47,58 @@ jobs:
           do
             kubectl logs -n default -c $container_name -l serving.knative.dev/service=${{ matrix.service }}
           done
+
+      - name: Down
+        if: ${{ always() }}
+        run: |
+          kn service delete --all
+
+  test-multi-loader:
+    name: Test Multi-Loader with Knative Deployment
+    env:
+      KIND_VERSION: v0.22.0
+      K8S_VERSION: v1.29
+      YAML_DIR: workloads/container
+    runs-on: ubuntu-20.04
+    strategy:
+      fail-fast: false
+      matrix:
+        service:
+          [
+            trace_func_go,
+          ]
+    steps:
+      - name: Set up common environment
+        uses: ./.github/workflows/ci-setup.yml
+
+      - name: Build and run multi-loader
+        run: go run tools/multi_loader/multi_loader.go --multiLoaderConfigPath tools/multi_loader/multi_loader_config.json
+
+      - name: Check multi_loader output
+        run: |
+          # check if there are 4 output folders: *_example_1_test, *_example_2_test, *_example_3_test & dry_run
+          folder_count=$(find data/out/multi-test/test-experiment -mindepth 1 -maxdepth 1 -type d | wc -l)
+          if [ "$folder_count" -ne 4 ]; then
+            echo "Output folder count is $folder_count, expected 4"
+            exit 1
+          else
+            echo "Output correct number of folders"
+          fi
+
+          # Check for errors in each output CSV file
+          for file in $(find . -name "*_example_1_test/example_1_test_duration_1.csv" -o -name "*_example_2_test/example_2_test_duration_1.csv" -o -name "*_example_3_test/example_3_test_duration_1.csv"); do
+            if [ ! -f "$file" ]; then
+              echo "File $file not found!"
+              exit 1
+            fi
+
+            if [ $(grep true "$file" | wc -l) -ne 0 ]; then
+              echo "Error found in $file"
+              exit 1
+            fi
+          done
+          echo "No errors found in output files"
+
       - name: Down
         if: ${{ always() }}
         run: |
